### ISSUE TITLE
ManiaExchange's old settings appear on the plugin's settings

### ISSUE THREAD

**Issue by GreepTheSheep** [RuurdBijlsma/tm-item-exchange#1]
Looks cool that we can display my tabs on your plugin Kappa
jk, just need to remove or change that to your settings if you have any

**Comment by RuurdBijlsma** [comment]
thx fixed it https://github.com/RuurdBijlsma/tm-item-exchange/commit/72f26b83a99dc1cdcdc0ee5769784eba12a5ae01
