### ISSUE TITLE
Crashes immediately

### ISSUE THREAD

**Issue by Hypn0tyk** [RuurdBijlsma/tm-item-exchange#5]
Item exchange immediately crashes immediately when attempting to interact with the sets tab in any fashion and happens 100% of the time.
![itemexchange error](https://github.com/RuurdBijlsma/tm-item-exchange/assets/53986111/d05098dc-9953-409c-b794-9231ea83712d)

**Comment by RuurdBijlsma** [comment]
If the error happened when you opened the tags list then i fixed it, will be published to openplanet soon
